### ISSUE TITLE
此仓库只收集2023级之后的内容吗

### ISSUE THREAD

**Issue by Anxcye** [sunshine-sutingjun/XMU-CS23-Learning-Resources#1]
此仓库只收集 2023 级及以后的内容吗？是否接受 2022 及更早内容的 PR？如目前大二、大三等的内容？

**Comment by Misaka-xxw** [comment]
已经收录了2022级的。应该是收集的

**Comment by sunshine-sutingjun** [comment]
完了，刚刚才看到

感谢pr！我会去调整一下LICENSE的！谢谢大佬帮助！

**Comment by sunshine-sutingjun** [comment]
> 此仓库只收集 2023 级及以后的内容吗？是否接受 2022 及更早内容的 PR？如目前大二、大三等的内容？

接受的：毕竟目的就是为了同学们获取资料方便，能够在上到这门课程的时候有及时的资料支持
